name:                Illustrations-Haskell
version:             0.1.0.0
github:              "L-Solutions/Illustrations-Haskell"
license:             BSD3
author:              "Benoît Fraikin"
maintainer:          "benoit.fraikin@usherbrooke.ca"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/L-Solutions/Illustrations-Haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src
    when:        
    - condition: false        
      other-modules: Paths_Illustrations_Haskell

executables:
  Illustrations-Haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Illustrations-Haskell
    when:        
    - condition: false        
      other-modules: Paths_Illustrations_Haskell

tests:
  Illustrations-Haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Illustrations-Haskell
    - tasty >= 1.4
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    when:        
    - condition: false        
      other-modules: Paths_Illustrations_Haskell
