
# Version
# 2022-06-08T15:12-0400

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/7.yaml

packages:
- .

extra-deps:
- git: https://github.com/L-Solutions/TextDecoration.git
  commit: 3317323eaea63b3b6b9dc3116462f8e6e2ebf134

